DROP TABLE IF EXISTS comments;

CREATE TABLE comments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    etag TEXT UNIQUE NOT NULL,
    author TEXT NOT NULL,
    text TEXT NOT NULL,
    likes INTEGER,
    timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
